# Generated by Django 4.1.1 on 2022-10-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='dept_image',
            field=models.ImageField(default='', upload_to='departments'),
        ),
    ]
