# Generated by Django 4.1.1 on 2022-10-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=255)),
                ('cust_phone', models.CharField(max_length=10)),
                ('cust_email', models.EmailField(max_length=254)),
                ('cust_msg', models.TextField()),
            ],
        ),
    ]
