# Generated by Django 4.1.1 on 2022-10-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='p_token',
            field=models.CharField(default='', max_length=10),
        ),
    ]
