# Generated by Django 4.1.1 on 2022-10-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_booking_p_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='p_token',
            field=models.IntegerField(default='', editable=False),
        ),
    ]
