# Generated by Django 4.1.1 on 2022-10-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_booking_p_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('p_phone', models.CharField(max_length=10)),
                ('p_address', models.TextField()),
                ('bitrhdate', models.DateField()),
                ('blood', models.CharField(max_length=10)),
            ],
        ),
    ]
