# Generated by Django 4.1.1 on 2022-10-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='p_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='patient',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
