# Generated by Django 4.1.1 on 2022-10-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_patient_p_email_alter_patient_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='blood',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='doctors',
            name='doc_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='doctors',
            name='doc_email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='doc_phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='doctors',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
