# Generated by Django 4.1.1 on 2022-10-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_doctors_blood_doctors_doc_address_doctors_doc_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='blood',
            field=models.CharField(choices=[('O+', 'O+'), ('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=10),
        ),
    ]
